version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: 111111
    ports:
      - '3309:3306'
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 111111
      DB_NAME: myapp
      DB_PORT: 3306
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        BACKEND_URL: http://backend:3001
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:3001
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8089:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: