services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=hoangnv
      - MYSQL_ROOT_PASSWORD=111111
    ports:
      - '3307:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

volumes:
  db:
