# version: '3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=todo_db
      - MYSQL_ROOT_PASSWORD=111111
    ports:
      - '3309:3306'
    expose:
      - 3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    # healthcheck:
    #   test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=111111
      - DB_NAME=todo_db
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
